#ifndef DRIVERS_MMU_H_
#define DRIVERS_MMU_H_
#include <stdint.h>

#define MMU_DIR_ENTRY_4KB_PRESENT         0x01
#define MMU_DIR_ENTRY_4KB_READ_ONLY       0x00
#define MMU_DIR_ENTRY_4KB_WRITABLE        0x02
#define MMU_DIR_ENTRY_4KB_USER            0x00
#define MMU_DIR_ENTRY_4KB_SUPERVISOR      0x04
#define MMU_DIR_ENTRY_4KB_WRITE_THROUGH   0x08
#define MMU_DIR_ENTRY_4KB_CASHE_DISABLE   0x10
#define MMU_DIR_ENTRY_4KB_ACCESSED        0x20
#define MMU_DIR_ENTRY_4KB_ADDRESS(S) ((S) & 0xFFFFF000)

#define MMU_DIR_ENTRY_4MB_PRESENT         0x01
#define MMU_DIR_ENTRY_4MB_READ_ONLY       0x00
#define MMU_DIR_ENTRY_4MB_WRITABLE        0x02
#define MMU_DIR_ENTRY_4MB_USER            0x00
#define MMU_DIR_ENTRY_4MB_SUPERVISOR      0x04
#define MMU_DIR_ENTRY_4MB_WRITE_THROUGH   0x08
#define MMU_DIR_ENTRY_4MB_CASHE_DISABLE   0x10
#define MMU_DIR_ENTRY_4MB_ACCESSED        0x20
#define MMU_DIR_ENTRY_4MB_DIRTY           0x40
#define MMU_DIR_ENTRY_4MB_GLOBAL          0x80
#define MMU_DIR_ENTRY_4MB_ATTRIBUTE_TABLE 0x0800
#define MMU_DIR_ENTRY_4MB_ADDRESS(S) (((S) & 0xFFC00000) | ((S) >> 0x13 & 0x001FE000))

#define MMU_TABLE_ENTRY_PRESENT           0x01
#define MMU_TABLE_ENTRY_READ_ONLY         0x00
#define MMU_TABLE_ENTRY_WRITABLE          0x02
#define MMU_TABLE_ENTRY_USER              0x00
#define MMU_TABLE_ENTRY_SUPERVISOR        0x04
#define MMU_TABLE_ENTRY_WRITE_THROUGH     0x08
#define MMU_TABLE_ENTRY_CASHE_DISABLE     0x10
#define MMU_TABLE_ENTRY_ACCESSED          0x20
#define MMU_TABLE_ENTRY_DIRTY             0x40
#define MMU_TABLE_ENTRY_ATTRIBUTE_TABLE   0x80
#define MMU_TABLE_ENTRY_GLOBAL            0x100
#define MMU_TABLE_ADDRESS(S) ((S) & 0xFFFFF000)

void mmu_init_4kb(void);
// void mmu_init_4mb(void);
void mmu_page_set(uint32_t addr, uint32_t page);

#endif//DRIVERS_MMU_H_
